### PR TITLE
fix import for Django 1.9

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
The changes are including:
* Demoproject made working and transformed to testing application
* Various filters are included in demoproject
* Automatic testing with Travis-ci on Django 1.5-1.8 and Python 2.6, 2.7 and 3.4
* Compatibility fixes for these versions
* Coverage with coveralls.org
* Readme update with actual filters

After pulling this request, you will have to enable Travis-ci tests and change Coveralls token in .coveralls.yml

**Comment by PetrDlouhy** [comment]
Hello, what about this PR?

**Comment by saxix** [comment]
oops... totally missed it. I'm going to merge, plan to package this weekend, thanks.

**Comment by saxix** [comment]
oops, totally missed it... I'm going to merge it, plan to release this weekend after some minor changes

**Comment by PetrDlouhy** [comment]
Thanks

**Pull request merged**
